version: "3.5"

services:
   db:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: postgres
        PGDATA: /data/postgres
      volumes:
        - db-data:/data/postgres
      expose:
        - 5432
      ports:
        - 5432:5432
      networks:
        - postgres
      restart: unless-stopped

   riddle_capture:
      image: riddle_capture
      build: ..
      environment:
        DATABASE_URL: postgresql://postgres:1234@db:5432/riddles
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - 5000:5000
      networks:
        - postgres
      depends_on:
        - db
      
   pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: test@gmail.com
          PGADMIN_DEFAULT_PASSWORD: 1234
     
      ports:
          - 80:80
      networks:
          - postgres
      restart: unless-stopped
      depends_on:
          - db
       
networks:
  postgres:
    driver: bridge

volumes:
  db-data: